use_frameworks!

target 'PrivacyInSwift_Example' do
  pod 'PrivacyInSwift', :path => '../'

  target 'PrivacyInSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
